### PR TITLE
call super's init method

### PR DESCRIPTION
**Pull request by roemhildtg**
#76

### CODE REVIEW

**Comment by justinbmeyer** [comment]
Thanks for the PR. We'll see eventually what's going on with the build.  (We are currently under-staffed (I just had a baby, Chasen is on a client), so any help others can give in the next few weeks is greatly appreciated).

**Comment by roemhildtg** [comment]
Poke @christopherjbaker

**Comment by chasenlehara** [comment]
Hey @roemhildtg, sorry this hasn’t been merged in yet. I’m back on open source and think I can take a look at the build issue either tomorrow afternoon or Monday. Sorry for the delay, we really appreciate you submitting PRs. 😊

**Comment by chasenlehara** [comment]
@roemhildtg If you have a moment, could you merge or rebase with master? I think I know what’s going on and would like to see if the tests will partially run now.

**Comment by roemhildtg** [comment]
@chasenlehara I updated this. Still failing for some reason.

**Comment by chasenlehara** [comment]
@roemhildtg It looks like Travis doesn’t set the environment variables required to make Sauce Labs work when PRs are made from someone outside the org, which was why it was failing. Sorry it took a while to get this merged & released, but it’s in [4.0.1](https://github.com/canjs/can-connect-feathers/releases/tag/v4.0.1) now!

**Pull request merged**
